// This file is generated by a tool. All changes will be overwritten.
import { Operation } from '@bearbytes/graphql-to-typescript'

// Scalar Types
export type String = string
export type Boolean = boolean
export type Int = number
export type Float = number
export type ID = string

// Fragment Types

// Input Types

// Operations
export default {
  getLocationInfo: `query getLocationInfo {\n  getLocation(ip: "189.59.228.170") {\n    country {\n      names {\n        en\n      }\n      geoname_id\n      iso_code\n    }\n    location {\n      latitude\n      longitude\n    }\n  }\n}` as Operation<
    'query',
    {},
    {
      getLocation: Nullable<{
        country: Nullable<{
          names: Nullable<{
            en: Nullable<String>
          }>
          geoname_id: Nullable<String>
          iso_code: Nullable<String>
        }>
        location: Nullable<{
          latitude: Nullable<String>
          longitude: Nullable<String>
        }>
      }>
    }
  >,
}

// Helper types
export type Nullable<T> = T | null
